import Link from 'next/link';

const SITE_URL = 'https://www.wondertravel.online';
const META = {
  title: 'Privacy Policy | WonderTravel',
  description: 'How WonderTravel collects, uses and protects your personal information when you book or use our cab service.'
};

// [PLACEHOLDER] fields must be filled in with real business/legal details before this page goes live.
const LAST_UPDATED = '[PLACEHOLDER: date, e.g. 1 August 2026]';
const LEGAL_ENTITY = '[PLACEHOLDER: registered business/entity name]';
const CONTACT_EMAIL = '[PLACEHOLDER: privacy/support email]';

export async function generateMetadata() {
  return {
    title: META.title,
    description: META.description,
    robots: { index: true, follow: true },
    alternates: { canonical: '/privacy' },
    openGraph: { title: META.title, description: META.description, url: '/privacy' },
    twitter: { title: META.title, description: META.description }
  };
}

export default function PrivacyPage() {
  const canonicalUrl = `${SITE_URL}/privacy`;
  const schema = {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: [
      { '@type': 'ListItem', position: 1, name: 'Home', item: `${SITE_URL}/` },
      { '@type': 'ListItem', position: 2, name: 'Privacy Policy', item: canonicalUrl }
    ]
  };

  return <article className="seo-guide page-shell legal-page">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} />
    <nav className="route-crumbs" aria-label="Breadcrumb">
      <Link href="/">Home</Link><span aria-hidden="true">/</span><span aria-current="page">Privacy Policy</span>
    </nav>

    <header className="seo-guide-hero">
      <span className="eyebrow">Legal</span>
      <h1>Privacy Policy</h1>
      <p>Last updated: {LAST_UPDATED}</p>
    </header>

    <section className="route-faq">
      <h2>1. Information we collect</h2>
      <p>{LEGAL_ENTITY} ("WonderTravel", "we", "us") collects information you provide directly, including name, phone number, email, pickup and destination addresses, travel dates and payment details, as well as information generated by using the Service, such as booking history and account activity.</p>
    </section>

    <section className="route-faq">
      <h2>2. How we use information</h2>
      <p>Information is used to create and manage bookings, assign drivers and vehicles, calculate fares, process payments, provide customer support, and send booking confirmations and updates. Aggregated, non-identifying data may be used to improve routes, pricing and the Service generally.</p>
    </section>

    <section className="route-faq">
      <h2>3. Sharing of information</h2>
      <p>Booking details necessary to complete a journey (pickup, destination, passenger name and contact number) are shared with the assigned driver. Payment information is processed by third-party payment providers and is not stored in full by WonderTravel. Information is not sold to third parties. It may be disclosed where required by law or to protect the safety of passengers, drivers or the public.</p>
    </section>

    <section className="route-faq">
      <h2>4. Cookies and tracking</h2>
      <p>The website uses cookies and similar technology to keep you signed in, remember booking preferences, and understand site usage. You can control cookies through your browser settings; disabling some cookies may affect booking functionality.</p>
    </section>

    <section className="route-faq">
      <h2>5. Data retention</h2>
      <p>Booking and account information is retained for as long as needed to provide the Service, meet legal or tax obligations, and resolve disputes, after which it is deleted or anonymised. [PLACEHOLDER: confirm specific retention periods.]</p>
    </section>

    <section className="route-faq">
      <h2>6. Your rights</h2>
      <p>You may request access to, correction of, or deletion of your personal information by contacting {CONTACT_EMAIL}. Some information may be retained where required by law or for legitimate business records, such as completed booking history.</p>
    </section>

    <section className="route-faq">
      <h2>7. Security</h2>
      <p>Reasonable technical and organisational measures are used to protect personal information, including encrypted transmission and access controls on account and booking data. No online service can guarantee absolute security.</p>
    </section>

    <section className="route-faq">
      <h2>8. Changes to this policy</h2>
      <p>This Privacy Policy may be updated from time to time. Material changes will be reflected by an updated "Last updated" date above.</p>
    </section>

    <section className="route-faq">
      <h2>9. Contact</h2>
      <p>Privacy questions or requests can be sent to {CONTACT_EMAIL}. For booking support, visit the <Link href="/help">help center</Link>.</p>
    </section>
  </article>;
}
